from typing import List, Dict, Any
from datetime import datetime, timedelta

DEPARTMENTS_DATA: List[Dict[str, Any]] = [
    {
        "id": "DEPT_SAN",
        "name": "Solid Waste Management & Sanitation",
        "hindiName": "ठोस अपशिष्ट प्रबंधन एवं स्वच्छता विभाग",
        "description": "Garbage clearing, street sweeping, public toilet sanitization, desilting of surface drains, and dead animal removal.",
        "icon": "Trash2",
        "standardSlaHours": 24,
        "emergencySlaHours": 6,
        "commonCategories": [
            "Overflowing Garbage Dustbins",
            "Door-to-door Waste Collection Delayed",
            "Dead Animal Removal",
            "Public Urinal Unhygienic / Damaged",
            "Dumping on Vacant Plot",
        ],
        "nodalOfficer": {
            "name": "Er. Rajesh Kumar Sharma",
            "designation": "Executive Engineer (Sanitation Cell)",
            "contact": "+91 94140 12890",
            "email": "ee.sanitation@smartcity.gov.in",
        },
        "helpline": "1800-180-2021",
    },
    {
        "id": "DEPT_WAT",
        "name": "Water Supply & Underground Drainage",
        "hindiName": "जल आपूर्ति एवं भूमिगत सीवरेज बोर्ड",
        "description": "Potable pipeline leakages, contaminated water supply, low water pressure, and sewer overflow.",
        "icon": "Droplets",
        "standardSlaHours": 24,
        "emergencySlaHours": 4,
        "commonCategories": [
            "Contaminated / Muddy Water Supply",
            "Main Pipeline Burst / Major Leakage",
            "No Water Supply in Ward",
            "Sewer Line Choking & Manhole Overflow",
            "Low Pressure Water Supply",
        ],
        "nodalOfficer": {
            "name": "Er. Priya Natarajan",
            "designation": "Superintending Engineer (Water Supply)",
            "contact": "+91 98450 44321",
            "email": "se.water@smartcity.gov.in",
        },
        "helpline": "1916",
    },
    {
        "id": "DEPT_PWD",
        "name": "Road Infrastructure & PWD",
        "hindiName": "सड़क आधारभूत संरचना एवं लोक निर्माण विभाग",
        "description": "Dangerous potholes, broken road stretches, collapsed footpaths, open storm drain culverts, and road cave-ins.",
        "icon": "HardHat",
        "standardSlaHours": 48,
        "emergencySlaHours": 12,
        "commonCategories": [
            "Deep Pothole / Hazard on Main Road",
            "Road Cave-in / Asphalt Peeling",
            "Broken Footpath / Paver Blocks Missing",
            "Uncovered Storm Water Drain Slab",
            "Speed Breaker Painting / Repair",
        ],
        "nodalOfficer": {
            "name": "Er. Amitav Sen",
            "designation": "Chief Engineer (Roads & Bridges)",
            "contact": "+91 98300 88712",
            "email": "ce.pwd@smartcity.gov.in",
        },
        "helpline": "1800-233-5566",
    },
    {
        "id": "DEPT_ELE",
        "name": "Electricity & Smart Street Lighting",
        "hindiName": "विद्युत आपूर्ति एवं स्ट्रीट लाइट प्रकोष्ठ",
        "description": "Hanging high-voltage wires, damaged transformer sparking, non-functional streetlights in dark spots, and feeder faults.",
        "icon": "Zap",
        "standardSlaHours": 12,
        "emergencySlaHours": 2,
        "commonCategories": [
            "Dark Stretch - Multiple Streetlights Off",
            "Hanging / Snapped Live Electric Wire",
            "Transformer Sparking / Oil Leak",
            "Electric Pole Tilting / Rusted Base",
            "Voltage Fluctuation / Power Outage",
        ],
        "nodalOfficer": {
            "name": "Er. Gurdeep Singh",
            "designation": "Assistant Executive Engineer (Electrical)",
            "contact": "+91 98720 33499",
            "email": "aee.electrical@smartcity.gov.in",
        },
        "helpline": "1912",
    },
    {
        "id": "DEPT_TRF",
        "name": "Traffic Management & Urban Transit",
        "hindiName": "यातायात प्रबंधन एवं सड़क सुरक्षा सेल",
        "description": "Malfunctioning traffic signals, missing zebra crossing signage, illegal vehicle encroachment on footpaths, and bus stop shelter damages.",
        "icon": "Compass",
        "standardSlaHours": 12,
        "emergencySlaHours": 3,
        "commonCategories": [
            "Traffic Signal Blinking / Total Blackout",
            "Illegal Commercial Vehicle Parking on Footpath",
            "Missing / Damaged Regulatory Signboard",
            "Traffic Congestion Bottleneck at Junction",
            "Broken Bus Shelter / Public Seat",
        ],
        "nodalOfficer": {
            "name": "Smt. Vandana Rao (IPS)",
            "designation": "Deputy Commissioner of Police (Traffic)",
            "contact": "+91 94480 66211",
            "email": "dcp.traffic@smartcity.gov.in",
        },
        "helpline": "1095",
    },
    {
        "id": "DEPT_HLT",
        "name": "Public Health & Vector Disease Control",
        "hindiName": "जन स्वास्थ्य एवं संक्रामक रोग नियंत्रण प्रकोष्ठ",
        "description": "Mosquito larvae breeding in stagnant water, fogging drive requests, stray animal bite menace, and unhygienic food stalls.",
        "icon": "ShieldAlert",
        "standardSlaHours": 24,
        "emergencySlaHours": 6,
        "commonCategories": [
            "Dengue/Malaria Mosquito Fogging Required",
            "Stagnant Water Pool in Open Plot",
            "Stray Dog Aggression / Pack Menace",
            "Unhygienic Food Stall next to Hospital/School",
            "Dead Animal Carcass Sanitization",
        ],
        "nodalOfficer": {
            "name": "Dr. Subhash Chandra Roy",
            "designation": "Chief Municipal Medical Health Officer",
            "contact": "+91 97110 55823",
            "email": "cmho.health@smartcity.gov.in",
        },
        "helpline": "104",
    },
    {
        "id": "DEPT_POL",
        "name": "Environmental Pollution & Air Quality",
        "hindiName": "पर्यावरण नियंत्रण एवं वायु गुणवत्ता निगरानी",
        "description": "Illegal garbage burning causing smoke, industrial effluent discharge, construction dust violation, and noise pollution past 10 PM.",
        "icon": "AlertTriangle",
        "standardSlaHours": 24,
        "emergencySlaHours": 4,
        "commonCategories": [
            "Open Biomass / Plastic Burning in Public",
            "Excessive Construction Dust without Green Net",
            "Loudspeaker / DG Set Noise Past 10 PM",
            "Industrial Effluent into Open Drain",
            "Tree Branch Falling Hazard",
        ],
        "nodalOfficer": {
            "name": "Dr. Ananya Mukherjee",
            "designation": "Regional Environmental Officer",
            "contact": "+91 98310 99450",
            "email": "ro.pollution@smartcity.gov.in",
        },
        "helpline": "1800-11-2040",
    },
]

# In-memory store
grievances_db: List[Dict[str, Any]] = [
    {
        "id": "GRV-2026-PWD-8492",
        "trackingNumber": "GRV-2026-PWD-8492",
        "title": "Severe Pothole Cluster with Exposed Rebars on 100ft Road",
        "rawCitizenInput": "100ft road Indiranagar near Metro pillar 42 mein bada gaddha hai, bikes slip ho rahi hain aur kal raat ek auto palat gaya tha. Bahut khatarnak hai.",
        "dictatedLanguage": "Hindi (Hinglish)",
        "translatedSummary": "Dangerous cluster of deep potholes with exposed rebars near Metro Pillar 42, 100ft Road Indiranagar. Multiple two-wheelers slipping and an auto-rickshaw overturned.",
        "departmentId": "DEPT_PWD",
        "departmentName": "Road Infrastructure & PWD",
        "category": "Deep Pothole / Hazard on Main Road",
        "subCategory": "Arterial Road Surface Defect",
        "urgency": "CRITICAL",
        "status": "WORK_IN_PROGRESS",
        "citizenName": "Ramesh Chandra Sharma",
        "citizenPhone": "+91 98450 12345",
        "citizenEmail": "ramesh.sharma@example.com",
        "isAnonymous": False,
        "wardNumber": "Ward 42 (Indiranagar North)",
        "locality": "Indiranagar 100ft Road",
        "landmark": "Near Metro Pillar 42, opposite State Bank",
        "city": "Bengaluru",
        "pincode": "560038",
        "attachments": [
            "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80"
        ],
        "createdAt": (datetime.utcnow() - timedelta(hours=8)).isoformat() + "Z",
        "updatedAt": (datetime.utcnow() - timedelta(hours=1)).isoformat() + "Z",
        "slaDeadline": (datetime.utcnow() + timedelta(hours=4)).isoformat() + "Z",
        "isSlaBreached": False,
        "timeline": [
            {
                "id": "t1",
                "timestamp": (datetime.utcnow() - timedelta(hours=8)).isoformat() + "Z",
                "status": "SUBMITTED",
                "title": "Grievance Lodged via Voice AI",
                "description": "Citizen dictated grievance in Hindi. AI auto-transcribed and detected high-risk accident zone.",
                "actor": "Ramesh Chandra Sharma",
                "actorRole": "CITIZEN",
            },
            {
                "id": "t2",
                "timestamp": (datetime.utcnow() - timedelta(hours=7, minutes=58)).isoformat() + "Z",
                "status": "AI_TRIAGED",
                "title": "AI Triaged to PWD Cell",
                "description": "Classified as CRITICAL accident hazard. 12-hour SLA initiated. Nodal Engineer notified.",
                "actor": "Samadhan AI Engine",
                "actorRole": "AI_SYSTEM",
            },
            {
                "id": "t3",
                "timestamp": (datetime.utcnow() - timedelta(hours=6)).isoformat() + "Z",
                "status": "ASSIGNED",
                "title": "Dispatched to Ward 42 PWD Squad",
                "description": "Assigned to Junior Engineer K. Murthy and Rapid Cold-Mix Pothole Crew #3.",
                "actor": "Er. Amitav Sen (Chief Engineer)",
                "actorRole": "EXECUTIVE_ENGINEER",
            },
            {
                "id": "t4",
                "timestamp": (datetime.utcnow() - timedelta(hours=3)).isoformat() + "Z",
                "status": "IN_INSPECTION",
                "title": "Site Inspection Completed",
                "description": "Inspector verified 3.2m x 1.8m crater with 15cm depth. Barricading placed to prevent accidents.",
                "actor": "Er. K. Murthy (Ward 42 JE)",
                "actorRole": "WARD_OFFICER",
            },
            {
                "id": "t5",
                "timestamp": (datetime.utcnow() - timedelta(hours=1)).isoformat() + "Z",
                "status": "WORK_IN_PROGRESS",
                "title": "Bitumen Asphalt Crew on Site",
                "description": "Compactor and hot-mix bitumen truck actively leveling the road surface. Target completion 2 hours.",
                "actor": "PWD Rapid Action Squad #3",
                "actorRole": "WARD_OFFICER",
            },
        ],
        "messages": [
            {
                "id": "m1",
                "sender": "AI_SYSTEM",
                "senderName": "Samadhan Alert",
                "timestamp": (datetime.utcnow() - timedelta(hours=8)).isoformat() + "Z",
                "text": "Your grievance has been auto-triaged to PWD Department under CRITICAL priority. Junior Engineer Er. K. Murthy has been notified.",
            },
            {
                "id": "m2",
                "sender": "OFFICER",
                "senderName": "Er. K. Murthy (Ward 42 JE)",
                "timestamp": (datetime.utcnow() - timedelta(hours=3, minutes=30)).isoformat() + "Z",
                "text": "Namaste Shri Ramesh ji, I have personally inspected the Indiranagar Metro Pillar 42 spot. Caution cones placed. Our asphalt repair crew is on the way.",
            },
            {
                "id": "m3",
                "sender": "CITIZEN",
                "senderName": "Ramesh Chandra Sharma",
                "timestamp": (datetime.utcnow() - timedelta(hours=2)).isoformat() + "Z",
                "text": "Thank you for the prompt action! Heavy evening traffic is coming, so please complete the repair before 5 PM if possible.",
            },
            {
                "id": "m4",
                "sender": "OFFICER",
                "senderName": "Er. K. Murthy (Ward 42 JE)",
                "timestamp": (datetime.utcnow() - timedelta(hours=1)).isoformat() + "Z",
                "text": "Road roller and hot-mix laying is underway right now. We will finish before 4:30 PM and post verification photos here.",
            },
        ],
        "aiSentimentScore": -0.85,
        "aiConfidenceScore": 0.98,
        "aiSuggestedActions": [
            "Dispatch emergency cold-mix asphalt patch truck",
            "Place retro-reflective cautionary traffic barricades",
            "Inspect upstream drainage to prevent future water-logging erosion",
        ],
        "assignedOfficer": {
            "name": "Er. K. Murthy",
            "designation": "Assistant Engineer (Ward 42)",
            "phone": "+91 94481 99201",
            "ward": "Ward 42 (Indiranagar)",
            "unit": "PWD East Zone Division",
        },
    },
]
